config/routes.rb
Rails.application.routes.draw do
  get 'tracks/create'

  get 'tracks/new'

  get 'tracks/edit'

  get 'tracks/show'

  get 'tracks/update'

  get 'tracks/destroy'

  get 'albums/create'

  get 'albums/new'

  get 'albums/edit'

  get 'albums/show'

  get 'albums/update'

  get 'albums/destroy'

  get 'bands/index'

  get 'bands/create'

  get 'bands/new'

  get 'bands/edit'

  get 'bands/show'

  get 'bands/update'

  get 'bands/destroy'

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
end

app/models/track.rb
class Track < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :session_token, :password_digest, uniqueness: true, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    user && user.is_password?(password) ? user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def create
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :logged_in?

  def login(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logged_in?
    !!current_user
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
  end

  def create
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )

    if @user
      login(@user)
      redirect_to new_session_url
    else
      flash.now[:errors] = [ "Invalid login credentials" ]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def create
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login(@user)
      flash.now[:success] = "Successfully created your account!"
      redirect_to new_session_url
    else
      flash.now[:errors] = [ "Invalid credentials" ]
      render :new
    end
  end

  def show
    render :show
  end

  private

  def user_params
    params.require(:users).permit(:email, :password)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/create.html.erb
<h1>Albums#create</h1>
<p>Find me in app/views/albums/create.html.erb</p>

app/views/albums/destroy.html.erb
<h1>Albums#destroy</h1>
<p>Find me in app/views/albums/destroy.html.erb</p>

app/views/albums/edit.html.erb
<h1>Albums#edit</h1>
<p>Find me in app/views/albums/edit.html.erb</p>

app/views/albums/new.html.erb
<h1>Albums#new</h1>
<p>Find me in app/views/albums/new.html.erb</p>

app/views/albums/show.html.erb
<h1>Albums#show</h1>
<p>Find me in app/views/albums/show.html.erb</p>

app/views/albums/update.html.erb
<h1>Albums#update</h1>
<p>Find me in app/views/albums/update.html.erb</p>

app/views/bands/create.html.erb
<h1>Bands#create</h1>
<p>Find me in app/views/bands/create.html.erb</p>

app/views/bands/destroy.html.erb
<h1>Bands#destroy</h1>
<p>Find me in app/views/bands/destroy.html.erb</p>

app/views/bands/edit.html.erb
<h1>Bands#edit</h1>
<p>Find me in app/views/bands/edit.html.erb</p>

app/views/bands/index.html.erb
<h1>Bands#index</h1>
<p>Find me in app/views/bands/index.html.erb</p>

app/views/bands/new.html.erb
<h1>Bands#new</h1>
<p>Find me in app/views/bands/new.html.erb</p>

app/views/bands/show.html.erb
<h1>Bands#show</h1>
<p>Find me in app/views/bands/show.html.erb</p>

app/views/bands/update.html.erb
<h1>Bands#update</h1>
<p>Find me in app/views/bands/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music App</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if logged_in? %>
      Welcome, <%= current_user.email %>!
      <form action="<%= session_url %>" method="post">
       <input type="hidden" name="_method" value="delete" />
       <input
          type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token%>" />
       <input type="submit" value="Sign Out" />
    <% else %>
      <a href="<%= new_session_url %>">Sign In</a>
    <% end %>

    <%= yield %>

  </body>

  <footer>
    Music for everyone.

  <%= yield :footer %>
  </footer>
</html>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %>
  <% end %>
<% end %>

app/views/tracks/create.html.erb
<h1>Tracks#create</h1>
<p>Find me in app/views/tracks/create.html.erb</p>

app/views/tracks/destroy.html.erb
<h1>Tracks#destroy</h1>
<p>Find me in app/views/tracks/destroy.html.erb</p>

app/views/tracks/edit.html.erb
<h1>Tracks#edit</h1>
<p>Find me in app/views/tracks/edit.html.erb</p>

app/views/tracks/new.html.erb
<h1>Tracks#new</h1>
<p>Find me in app/views/tracks/new.html.erb</p>

app/views/tracks/show.html.erb
<h1>Tracks#show</h1>
<p>Find me in app/views/tracks/show.html.erb</p>

app/views/tracks/update.html.erb
<h1>Tracks#update</h1>
<p>Find me in app/views/tracks/update.html.erb</p>

app/views/users/new.html.erb
<section class="page">
  <div class="centered-box">
    <h1 class='header'>New User</h1>

    <%= render 'shared/errors' %>

    <form action="<%= users_url %>" method="post">
      <input
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">

      <p>
        <label>Email
          <input type="text" name="users[email]">
        </label>
      </p>

      <p>
        <label>Password
          <input type="password" name="users[password]">
        </label>
      </p>

      <button type="submit" name="submit">submit</button>
    </form>
  </div>

  <% content_for :footer do %>
    Create an account and start jammin'.
  <% end %>
</section>

app/views/users/show.html.erb
<h1 class='header'>Profile</h1>

  <p>
    Email: <%= current_user.email %>
  </p>